### ISSUE TITLE
No character or enemies appear at level 4

### ISSUE THREAD

**Issue by kedpak** [EdwardDunn/Platform-Game#77]
Today when I reached level 4, there are no enemies are character on screen. And the score will just keep increasing infinitely. Also, is there a reason why the score keeps reseting when a new level is reached? I am thinking of tweaking this.

**Comment by EdwardDunn** [comment]
@kedpak Yeah it might be better if the score continued in new levels rather than resetting. A future task is to add a leader board, so this would help. 

The enemy number for each level is random, so sometimes there may be no enemies. Did you test this multiple times? 

I think this should also be changed so that there is a minimum for the random number to ensure this does not occur.
